Repository cta-observatory/nectarchain, pull requests merged in 2025-02, with the labels that each got.

#174 Use context manager to decrease memory load in DQM
  src/nectarchain/dqm/start_dqm.py
Labels: enhancement

#175 Update Apptainer recipe
  Singularity
Labels: enhancement

#179 Fixing API documentation for ReadTheDocs
  docs/conf.py
Labels: bug

#180 Fix deployment on PyPI
  README.rst
Labels: bug

#181 Improvement of the data management and naming of containers files
  notebooks/tool_implementation/tuto_photostat.py
  src/nectarchain/data/management.py
  src/nectarchain/makers/calibration/gain/flatfield_spe_makers.py
  src/nectarchain/makers/calibration/gain/photostat_makers.py
  src/nectarchain/makers/charges_makers.py
  src/nectarchain/makers/extractor/utils.py
  src/nectarchain/user_scripts/ggrolleron/gain_PhotoStat_computation.py
  src/nectarchain/user_scripts/ggrolleron/gain_PhotoStat_computation.sh
  src/nectarchain/user_scripts/ggrolleron/gain_SPEfit_combined_computation.py
  src/nectarchain/user_scripts/ggrolleron/gain_SPEfit_computation.py
  src/nectarchain/user_scripts/ggrolleron/gain_SPEfit_computation.sh
  src/nectarchain/user_scripts/ggrolleron/load_wfs_compute_charge.py
  src/nectarchain/user_scripts/ggrolleron/load_wfs_compute_charge.sh
  src/nectarchain/utils/error.py
Labels: bug, enhancement

#184 Add first versioning for RTD
  docs/_static/switcher.json
Labels: documentation

#185 Add versions to RTD
  docs/_static/switcher.json
Labels: documentation

#187 fix tool's logger to properly log exception
  src/nectarchain/makers/calibration/gain/photostat_makers.py
  src/nectarchain/makers/core.py
Labels: bug
